* 2017 11 28, Tuesday

This is my last week at @Flipkart! Thursday- November 30th will be my last day
of work, after which I go on a 4-month sabbatical. I have to return all my IT
assets. Bye bye MacBook Pro :'-(

TODOs for this week:

1) Write a blog post about Outreachy selection and/or a project description.
Writing one every two weeks is one of the mandatory parts of the internship. I
did set up a blog last week using hugo at aishpant.github.io but it's empty.

2) Back up data from office laptop.

3) Set up the borrowed laptop with the linux codebase and all my dotfiles.

4) Become friends with tmux.

5) Go through the vimtutor tutorial 3 more times.

* 2017 11 29, Wednesday

Finished one iteration of the vimtutor tutorial. Added first proper blog post on
my blog! It's kind of temporary and rough but it's finally a start! With this
done, I sent off the links to Outreachy organisers.

Cleaned up the deployment of personal website. Added aishpant.github.io as a
submodule to hugo content repo. Didn't know that tracking of two different repos
was possible in this way.

Currently working through a Markdown tutorial. I want to get this right. Should
add social links to the blog site.

The hard drive was delivered today. Backed up all office data. The other
important stuff is tracked already. Not much left to do here. Things move
forward very slowly. Reviewed a pull request.

Oh that reminds me I should backup dotfiles from my VM also. I'll do that.
