* 2017 11 28, Tuesday

This is my last week at @Flipkart! Thursday- November 30th will be my last day
of work, after which I go on a 4-month sabbatical. I have to return all my IT
assets. Bye bye MacBook Pro :'-(

TODOs for this week:

1. Write a blog post about Outreachy selection and/or a project description. Writing one every two weeks is one of the mandatory parts of the internship. I did set up a blog last week using hugo at aishpant.github.io but it's empty.

2. Back up data from office laptop.

3. Set up the borrowed laptop with the linux codebase and all my dotfiles.

4. Become friends with tmux.

5. Go through the vimtutor tutorial 3 more times.

* 2017 11 29, Wednesday

Finished one iteration of the vimtutor tutorial. Added first proper blog post on
my blog! It's kind of temporary and rough but it's finally a start! With this
done, I sent off the links to Outreachy organisers.

Cleaned up the deployment of personal website. Added aishpant.github.io as a
submodule to hugo content repo. Didn't know that tracking of two different repos
was possible in this way.

Currently working through a Markdown tutorial. I want to get this right. Should
add social links to the blog site.

The hard drive was delivered today. Backed up all office data. The other
important stuff is tracked already. Not much left to do here. Things move
forward very slowly. Reviewed a pull request.

Oh that reminds me I should backup dotfiles from my VM also. I'll do that.

* 2017 11 30, Thursday

Last day of work. Feeling odd. Mixed feelings. Went out in the evening.

* 2017 12 01, Friday

Spent most of the day struggling with Arch Linux. I fail to see how this is any
better than Ubuntu or Debian or Mint or Fedora.

`pacman` is the default PACkage MANager here. The tldr page is enough to get
started. The other, `yaourt` works just like pacman and contains scripts to
download the lastest packages that have not made into official repos yet.

I should do a newbie write-up on how to compile linux kernel in arch.

* 2017 12 04, Monday

Doesn't really feel like a Monday. Cold weather (for Bangalore) and lazy.
Needed one chai and two cups of coffee to wake up.

TIL about the PBKDF2 (Password Based Key Derivation Function v2). Maybe I could
talk about this at a PWL. My day job has never involved reading white papers.
And if I don't read any, I'm afraid I might become out-of-date. Another aspect
of this, which interests me is speaking in public. I don't think I have ever
done it out of choice. I have reached a point now where it is necessary to
embrace fear.

Read lots of blog posts by Jeffrey Goldberg (Defender Against The Dark Arts at
1Password). In each iteration, password or the transformed key is encrypted by
a process called HMAC-SHA1(?).

Password hashing algorithms are designed to be purposefully slow in contrast to
crypotgraphic hashing functions. Some good password hashing schemes:
1. bcrypt
2. scrypt
3. PBKDF2

Usually salting is added before passwords are encrypted. For eg. adding a
random string at the beginning or the end. This is done to prevent check
against a pre-computed list of hashes. The salt is not a secret. It's random
and uniquely generated per password.

Today I also learnt how 2-step authentication works using HOTP or TOTP
protocols! I am already on GNU pass but I still had a couple of old weak
passwords. It was a pain trying to figure out how to enable copy-paste on ICICI
bank website. You wouldn't expect bank websites to be clueless about security.

Read 2 chapters of I,Robot. This is my first Asimov. Why did I not read him
before?

[Giorgio by Morodor - Daft Punk](https://youtu.be/zhl-Cs1-sG4) - Beautiful
intro, all 9 minutes of the music is breathtaking.

Caffeine count - 2 tulsi masala chais, 1 filter coffee, 1 cold coffee, 1 black tea
